name: Build APK (Buildozer Docker)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull kivy/buildozer Docker image
        run: docker pull kivy/buildozer:latest

      - name: Build APK
        run: |
          mkdir -p $HOME/.buildozer
          docker run --rm \
            -v "${{ github.workspace }}":/home/user/hostcwd \
            -v "$HOME/.buildozer":/home/user/.buildozer \
            -w /home/user/hostcwd \
            kivy/buildozer:latest \
            buildozer -v android debug
          sudo chown -R $(id -u):$(id -g) bin || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
