name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git zip unzip \
          openjdk-17-jdk wget libncurses5 libstdc++6 libffi-dev libssl-dev \
          libsqlite3-dev libjpeg-dev zlib1g-dev
        pip install --upgrade pip
        pip install buildozer Cython==0.29.36

    - name: Build APK
      run: |
        buildozer init || true
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Calculator-APK
        path: bin/*.apk
