image: kivy/buildozer:latest

stages:
  - build

variables:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

before_script:
  - apt-get update -y
  - apt-get install -y python3-pip zip git openjdk-11-jdk

android_build:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install buildozer cython virtualenv
    - buildozer android clean
    - buildozer android debug
  artifacts:
    paths:
      - bin/*.apk
    expire_in: 1 week
  only:
    - main
    - master
