name: Build APK (Buildozer Docker)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Reduced to 60 minutes (default), increase if builds need longer

    env:
      DOCKER_BUILDKIT: "0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for buildozer.spec
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "ERROR: buildozer.spec not found! Please create it with 'buildozer init'."
            exit 1
          fi

      - name: Prepare Buildozer cache directory
        run: mkdir -p $HOME/.buildozer

      - name: Pull Buildozer Docker image
        run: docker pull kivy/buildozer:latest

      - name: Build APK using Buildozer in Docker
        run: |
          mkdir -p bin
          docker run --rm \
            -v "${{ github.workspace }}":/home/user/hostcwd \
            -v "$HOME/.buildozer":/home/user/.buildozer \
            -w /home/user/hostcwd \
            kivy/buildozer:latest \
            /bin/bash -c "buildozer -v android debug"
          sudo chown -R $(id -u):$(id -g) bin || true

      - name: List output files (debug)
        run: |
          echo "APK files in bin/:"
          ls -la bin/*.apk || echo "No APK produced!"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-apk
          path: bin/*.apk
